In [196]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
sns.set_theme()

# optimization
from scipy import optimize

# For quick OLS
#import statsmodels.formula.api as smf

# Import our toolbox
import clogit as clogit
import mlogit_ante as mlogit
import estimation as est

# Read in data

The dataset, `cars.csv`, contains cleaned and processed data. If you want to make changes, the notebook, `materialize.ipynb`, creates the data from the raw source datsets. 

In [197]:
cars = pd.read_csv('cars.csv')
lbl_vars = pd.read_csv('labels_variables.csv')
lbl_vals = pd.read_csv('labels_values.csv')

# convert from dataframe to dict
lbl_vals = {c: lbl_vals[c].dropna().to_dict() for c in lbl_vals.columns}

In [198]:
lbl_vars.set_index('variable', inplace=True)

## Overview of the dataset

In [199]:
lbl_vars.join(cars.mean(numeric_only=True).apply(lambda x: f'{x: .2f}').to_frame('Mean'))

label  \
variable                                                      
ye                         year (=first dimension of panel)   
ma                      market (=second dimension of panel)   
co                   model code (=third dimension of panel)   
zcode     alternative model code (predecessors and succe...   
brd                                              brand code   
type                                name of brand and model   
brand                                         name of brand   
model                                         name of model   
org       origin code (demand side, country with which c...   
loc       location code (production side, country where ...   
cla                                   class or segment code   
home      domestic car dummy (appropriate interaction of...   
frm                                               firm code   
qu                  sales (number of new car registrations)   
cy                  cylinder volume or displacement (in cc)   
hp                                       horsepower (in kW)   
we                                           weight (in kg)   
pl                   places (number, not reliable variable)   
do                    doors (number, not reliable variable)   
le                                           length (in cm)   
wi                                            width (in cm)   
he                                           height (in cm)   
li1       measure 1 for fuel efficiency (liter per km, a...   
li2       measure 2 for fuel efficiency (liter per km, a...   
li3       measure 3 for fuel efficiency (liter per km, a...   
li                average of li1, li2, li3 (used in papers)   
sp                                  maximum speed (km/hour)   
ac        time to acceleration (in seconds from 0 to 100...   
pr         price (in destination currency including V.A.T.)   
princ     =pr/(ngdp/pop): price relative to per capita i...   
eurpr     =pr/avdexr: price in common currency (in SDR t...   
exppr                 =pr/avexr: price in exporter currency   
avexr     av. exchange rate of exporter country (exporte...   
avdexr    av. exchange rate of destination country (dest...   
avcpr          av. consumer price index of exporter country   
avppr          av. producer price index of exporter country   
avdcpr      av. consumer price index of destination country   
avdppr      av. producer price index of destination country   
xexr                                           avdexr/avexr   
tax                                          percentage VAT   
pop                                              population   
ngdp      nominal gross domestic product of destination ...   
rgdp                            real gross domestic product   
engdp     =ngdp/avdexr: nominal gdp in common currency (...   
ergdp                                           =rgdp/avexr   
engdpc    =engdp/pop: nominal gdp per capita in common c...   
ergdpc                                           =ergdp/pop   
s                                market share (qu / qu_tot)   
qu_tot                      total sales in this market-year   
inc                                  avg. income per capita   

                         Mean  
variable                       
ye                      84.50  
ma                       3.00  
co                     207.50  
zcode                  177.76  
brd                     16.79  
type                      NaN  
brand                     NaN  
model                     NaN  
org                      2.72  
loc                      5.17  
cla                      2.30  
home                     0.32  
frm                     14.50  
qu                   35606.68  
cy                    1337.09  
hp                      50.10  
we                     934.49  
pl                       4.88  
do                       3.55  
le                     409.24  
wi                     163.44  
he                     140.46  
li1      

In [200]:
temp = lbl_vars.join(cars.mean(numeric_only=True).apply(lambda x: f'{x: .2f}').to_frame('Mean'))
temp['label']['princ']

'=pr/(ngdp/pop): price relative to per capita income (often used in demand model)'

# Set up for analysis

In [201]:
price_var = 'princ'

In [202]:
cars['logp'] = np.log(cars[price_var])

In [203]:
# new variable: price elasticity heterogeneous for home-region 
cars['logp_x_home'] = cars[price_var] * cars['home']

# Scaling for numerical stability
cars['cy']/=1000
cars['hp']/=100
cars['we']/=1000

### Dummy variables

For working with matrices, we want to have a column for each dummy variable. 

In [204]:
categorical_var = 'brand' # name of categorical variable
dummies = pd.get_dummies(cars[categorical_var]) # creates a matrix of dummies for each value of dummyvar
x_vars_dummies = list(dummies.columns[1:].values) # omit a reference category, here it is the first (hence columns[1:])

# add dummies to the dataframe 
assert dummies.columns[0] not in cars.columns, f'It looks like you have already added this dummy to the dataframe. Avoid duplicates! '
cars = pd.concat([cars,dummies], axis=1)

In [205]:
# NB! Let's take a look at the reference category
dummies.columns[0] #This is BMW
# Something might be going on 

'BMW'

In [206]:
# Dropping columns
cars = cars.dropna(axis=1)

### `x_vars`: List of regressors to be used 

In [207]:
x_vars = ['logp', 'home', 'logp_x_home', 'cy', 'hp', 'we', 'li', 'he'] + x_vars_dummies
# If we include dummies for the brand, the 3-D matrix x becomes singular. Why?
# 
print(f'K = {len(x_vars)} variables selected.')

K = 40 variables selected.


In [208]:
cars['co'].nunique() #Different car models - some cars are in the top 40 most sold for a market and/or year

285

In [209]:
K = len(x_vars) #The "household" characteristics
N = cars.ma.nunique() * cars.ye.nunique() #The market-year 'i'
J = 40 #The 40 different cars
x = cars[x_vars].values.reshape((N,J,K))

In [210]:
y = cars['s'].values #The market shares 
y = y.reshape((N,J)) #The market shares in market-year N for J=40 different cars

In [211]:
# Let's look at a particular 'market-year' to see what is going on

test = cars[(cars['ma']==1) & (cars['ye']==70)] 


# Interpretation: Each 'market-year', the top 40 most selling cars make up about 99.99% of all cars sold.
    # Each market-year share column (called "s" in the data) sums to one


In [212]:
test

ye  ma   co  zcode  brd                               type      brand  \
0   70   1   15     14    2                       audi 100/200       audi   
1   70   1   26     35    4            citroen 2 CV 6 - 2 CV 4    citroen   
2   70   1   36     36    4                      citroen dyane    citroen   
3   70   1   64     67    7                           fiat 128       fiat   
4   70   1   71     80    8                        ford escort       ford   
5   70   1  134    159   16                   mercedes 200-300   mercedes   
6   70   1  165    197   19                        opel kadett       opel   
7   70   1  172    194   19                        opel rekord       opel   
8   70   1  186    202   20                        peugeot 504    peugeot   
9   70   1  187    207   20                        peugeot 304    peugeot   
10  70   1  196    227   22                          renault 4    renault   
11  70   1  212    337   22                         renault 16    renault   
12  70   1  213    338   22                          renault 6    renault   
13  70   1  214    319   22                         renault 12    renault   
14  70   1  217    242   36                         rover mini      rover   
15  70   1  269    284   29                     toyota corolla     toyota   
16  70   1  291    305   30  volkswagen coccinelle-beetle,1200         VW   
17  70   1  406     15    2                         audi 60-75       audi   
18  70   1  407    360    2               audi prinz 1000-1200       audi   
19  70   1  410    363    3            BMW 1502-1600-1602-1802        BMW   
20  70   1  412     17    3                           BMW 2002        BMW   
21  70   1  417     31    4                        citroen ami    citroen   
22  70   1  418    366    4                    citroen d-ds 20    citroen   
23  70   1  422    370   40                             daf 33        daf   
24  70   1  429    375    7                           fiat 124       fiat   
25  70   1  430    375    7                fiat 124 spec/sport       fiat   
26  70   1  431    376    7                      fiat 125-125S       fiat   
27  70   1  435    379    7                           fiat 850       fiat   
28  70   1  437     79    8                        ford 12-15M       ford   
29  70   1  439     78    8                        ford 20-26M       ford   
30  70   1  468    187   18                 nissan/datsun 1000     nissan   
31  70   1  488    418   19    opel/vxhall viva/firenze/magnum       opel   
32  70   1  490    420   20                        peugeot 204    peugeot   
33  70   1  491    421   20                        peugeot 404    peugeot   
34  70   1  497    426   22                       renault 8-10    renault   
35  70   1  521    446   46                  talbot/simca 1000  tal/simca   
36  70   1  524    448   46             talbot/simca 1301-1501  tal/simca   
37  70   1  536    301   30               volkswagen berl/1600         VW   
38  70   1  541    293   31                          volvo 140      volvo   
39  70   1  544    386    8                           ford 17M       ford   

        model  org  loc  ...  seat  skoda  suzuki  tal/hillman  tal/matra  \
0     100/200    2    4  ...     0      0       0            0          0   
1        2CV6    1    3  ...     0      0       0            0          0   
2       dyane    1    3  ...     0      0       0            0          0   
3         128    3    5  ...     0      0       0            0          0   
4      escort    2    4  ...     0      0       0            0          0   
5         200    2    4  ...     0      0       0            0          0   
6       kadet    2    4  ...     0      0       0            0          0   
7      record    2    4  ...     0      0       0            0          0   
8         504    1    3  ...     0      0       0            0          0   
9         304    1    3  ...     0      0       0            0          0   

In [213]:
test['s'].sum() #The share of total sales for the top 40 most cars sum to one

0.9999999999999979

$$
u_{i j h}=\mathbf{x}_{i j} \boldsymbol{\beta}_o+\varepsilon_{i j h}, \quad j=1, \ldots, J
$$

where: 

- $i$ is the $\textit{country-year}$ pair
- $j$ is the alternative car
- $h$ is the household

First off: Are we: 

    1. interested in the marginal utility of a car's characteristic (conditional logit) or 
    
    2. the change in utility of car $j$ relative to car 1 given a change in household characteristics?

In this assignment, we are examning home bias - that is the propensity to choose a car manufactured in the home country. We are therefore interested in 1) and will use a conditional logit model.

In [214]:
# Our conditional choice probabilities
# For coefficients ('theta') starting at zero, these must be equal to zero
# Intuition: No utility is gained by any car characteristics, thus market shares must be equal. Let's check this.
theta_start = clogit.starting_values(y,x)
ccp = clogit.choice_prob(theta_start, x)
(ccp == 1/J) # all choice probs are equal to each other.

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [215]:
# In the first market-year, what are the choice-probs? (Given individuals place no weight on any car characteristics)
ccp.sum(axis=1) #Summing over the columns J equal one. Goods

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [216]:
print(ccp.shape)
np.unique(ccp) #Checking if we have any NaN

(150, 40)


array([0.025])

In [217]:
temp_df = pd.DataFrame(x[50]) #Looking at the 50th market-year
temp_df.columns=x_vars
temp_df.head()

logp  home  logp_x_home   cy    hp     we   li     he  MCC   VW  ...  \
0 -0.438650   0.0     0.000000  1.3  0.63  0.940  7.8  135.0  0.0  0.0  ...   
1 -0.226922   0.0     0.000000  1.8  0.66  1.050  7.6  139.5  0.0  0.0  ...   
2 -0.143563   0.0     0.000000  1.6  0.75  1.080  8.5  138.0  0.0  0.0  ...   
3  0.407682   0.0     0.000000  2.0  1.10  1.425  9.8  141.0  0.0  0.0  ...   
4 -0.891653   1.0     0.409978  1.0  0.33  0.640  5.0  135.5  0.0  0.0  ...   

   seat  skoda  suzuki  tal/hillman  tal/matra  tal/simca  tal/sunb  talbot  \
0   0.0    0.0     0.0          0.0        0.0        0.0       0.0     0.0   
1   0.0    0.0     0.0          0.0        0.0        0.0       0.0     0.0   
2   0.0    0.0     0.0          0.0        0.0        0.0       0.0     0.0   
3   0.0    0.0     0.0          0.0        0.0        0.0       0.0     0.0   
4   0.0    0.0     0.0          0.0        0.0        0.0       0.0     0.0   

   toyota  volvo  
0     0.0    0.0  
1     0.0    0.0  
2     0.0    0.0  
3     0.0    0.0  
4     0.0    0.0  

[5 rows x 40 columns]

In [218]:
res = est.estimate(clogit.q2, theta_start, y, x)

Optimization terminated successfully.
         Current function value: 3.472067
         Iterations: 288
         Function evaluations: 11931
         Gradient evaluations: 291


In [219]:
tab_1 = pd.DataFrame(res['theta'], index=x_vars)
tab_1

0
logp        -0.168480
home         1.459933
logp_x_home -0.140409
cy          -0.119736
hp          -1.394324
we           0.658685
li          -0.037182
he          -0.011397
MCC         -1.159889
VW           0.212468
alfa romeo  -0.673681
audi        -0.105014
citroen     -0.431305
daewoo      -0.444989
daf         -0.709983
fiat        -0.090800
ford         0.058229
honda       -0.259776
hyundai     -0.646455
innocenti   -1.309225
lancia      -0.884777
mazda       -0.341090
mercedes     0.506502
mitsubishi  -0.431109
nissan      -0.128545
opel         0.012914
peugeot     -0.041120
renault      0.054324
rover       -0.366944
saab        -0.701979
seat        -0.683925
skoda       -0.794853
suzuki      -1.085224
tal/hillman -1.236834
tal/matra   -2.729882
tal/simca   -0.393954
tal/sunb    -3.356260
talbot      -0.377906
toyota      -0.023751
volvo       -0.014048

In [220]:
theta_hat = res['theta']

In [221]:
x[:, 0, 1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [222]:
ccp_res = clogit.choice_prob(theta_hat, x)
own_price_elas=(1-ccp_res)*res['theta'][0]

In [223]:
own_price_elas.mean()

-0.16426759510641578

In [224]:
market_share = cars['s'].values.reshape((N,J))
market_share[0] # For the first market-year, what are the observed market shares of the 40 different cars?

array([0.01129646, 0.01464355, 0.02803195, 0.03263421, 0.03974679,
       0.02786459, 0.04393066, 0.0460226 , 0.02091936, 0.01025049,
       0.03598131, 0.02991469, 0.03347098, 0.01861823, 0.03075147,
       0.03911921, 0.05857422, 0.01255162, 0.00920452, 0.00878613,
       0.00920452, 0.01548033, 0.01945501, 0.03127445, 0.01799065,
       0.01380678, 0.00962291, 0.03012388, 0.03179743, 0.01045968,
       0.01108726, 0.02259291, 0.02322049, 0.02510324, 0.02656759,
       0.05899261, 0.01589872, 0.02091936, 0.03233297, 0.02175614])

In [225]:
ccp_res[0] # For the first market-year, what are the estimated market shares of the 40 different cars given our control variables?

array([0.0181127 , 0.02133926, 0.02251711, 0.02442748, 0.03577578,
       0.02872879, 0.02948488, 0.02951582, 0.01905587, 0.02337763,
       0.03514152, 0.02631775, 0.03394901, 0.02843779, 0.02418472,
       0.02296615, 0.03820471, 0.02299015, 0.02617499, 0.01790193,
       0.01435771, 0.0224409 , 0.01177587, 0.01895712, 0.02326818,
       0.02057042, 0.01618421, 0.03343225, 0.03150188, 0.01811986,
       0.02324264, 0.02942917, 0.02890994, 0.0211854 , 0.03399321,
       0.02248282, 0.02113525, 0.03645776, 0.01804484, 0.02590652])

In [226]:
E_own   = np.zeros((N, J))
E_cross = np.zeros((N, J))
dpdx    = np.zeros((N, J))
k_price = 0

for j in range(J):
    # A. copy 
    x2 = x.copy()
    
    # B. increase price just for car j 
    rel_change_x = 1e-3

    ###UNCOMMENT FOR PRICES NOT IN LOG####
    #x2[:, j, k_price] *= (1+rel_change_x)
    
    x2[:, j, k_price] += np.log(1+rel_change_x) # Prices are in logs -> log(price)+log(1+0.001) --> relative change of something small to the (log)price

    # C. evaluate CCPs
    ccp2 = clogit.choice_prob(theta_hat, x2) # Fill in 
    
    # D. percentage change in CCPs 
    rel_change_y = ccp2/ccp_res-1 # Fill in 
    
    # E. elasticities 
    elasticity = rel_change_y/rel_change_x # Fill in 
    
    E_own[:, j] = elasticity[:, j] # Fill in 
    
    k_not_j = [k for k in range(J) if k != j] # indices for all other cars than j -> this list changes as we loop through j
    E_cross[:, j] = elasticity[:, k_not_j].mean(axis=1) # Fill in: Avg. among the cars k_not_j, taking the average over axis=1 (the cars, not the individuals!)

In [227]:
print(f'Own-price elasticity:  {np.mean(E_own).round(4)}')
print(f'Cross-price elasticity: {np.mean(E_cross).round(4)}')

Own-price elasticity:  -0.1642
Cross-price elasticity: 0.0042


In [233]:
def marg_effect_discrete(betahat, x0, x1):
    # Calculate the probabilities of x1 and x0, using betahat of the latest model estimation.
    # Then substract the probability vector of x0 from the probability vector of x1.
    prob_x1 = clogit.choice_prob(betahat, x1) # Fill in: choice probability matrix at x1 
    prob_x0 = clogit.choice_prob(betahat, x0) # Fill in: choice probability matrix at x0
    return (prob_x1 - prob_x0).flatten()

In [ ]:
def marg_effect_continuous(thetahat, theta_k, x):
    '''
        thetahat: (N,J-1) matrix of coefficients
        theta_k: J-vector of coefficients on the k'th covariate
        x: (N,K) matrix (possibly just N=1) of covariates
    '''
    N,K = x.shape
    K,J_1 = thetahat.shape
    J = J_1 + 1 # only coefficients for J-1 alternatives 
    
    # 0. input checks 
    assert theta_k.ndim     == 2, f'"theta_k" should not be flattened (ndim==2 required)'
    assert theta_k.shape[0] == J, f'"theta_k" should be {J=}, but got {theta_k.shape[0]}'
    assert theta_k.shape[1] == 1, f'"theta_k" must be a column J-vector'
    
    # 1. compute derivative: return flattened (N*J, )
    prob, _ = mlogit.choice_prob(thetahat, x) 
    # Fill in 

    start = (prob@theta_k)

    margeff = prob.T*(theta_k-start)

    return margeff

In [236]:
k_home = 1
k_logp = 0
k_logp_x_home = 2

x0 = x.copy()
x0[:, :, k_home]=0

x1 = x.copy()

x1[:, :, k_home] = 1.0 

---

Old stuff

---

In [573]:
np.linalg.matrix_rank(x) # something is not right when you include the car-brand dummies -> rank-condition is not fulfilled -> matrix becomes singular
# Reference category is 'BMW'
# Could be that none of the top 40 cars sold in a given year and market is home-made and/or that they are BMW's -> some column(s) then become(s) zero.

array([21, 21, 23, 21, 23, 24, 24, 23, 23, 21, 22, 22, 23, 21, 21, 21, 22,
       22, 22, 21, 21, 20, 21, 21, 22, 21, 21, 22, 22, 22, 20, 22, 22, 21,
       23, 23, 22, 19, 19, 19, 20, 20, 20, 19, 20, 21, 20, 20, 21, 21, 20,
       20, 19, 19, 20, 20, 21, 20, 20, 19, 20, 21, 21, 23, 21, 20, 20, 21,
       23, 21, 22, 22, 22, 21, 21, 21, 21, 21, 21, 22, 22, 22, 23, 24, 24,
       23, 24, 23, 23, 22, 20, 21, 22, 19, 20, 20, 20, 20, 20, 20, 21, 21,
       21, 20, 20, 21, 21, 20, 21, 18, 20, 20, 20, 21, 22, 23, 24, 23, 26,
       24, 22, 22, 24, 26, 24, 24, 23, 20, 21, 20, 21, 23, 21, 21, 20, 21,
       21, 21, 21, 20, 20, 21, 20, 21, 21, 20, 22, 22, 23, 21],
      dtype=int64)

In [574]:
# So in each year, let's define 40 different choices from j=0,...,40 
# NB! Remember that one particular car model may appear multiple times over different years and/or markets.
# This is slightly confusing -> basically, we model the 40 different choices, even though the same choice may appear again later

In [575]:
# Repeating the choice of 40 different cars in each market-year --> 6000 obs
# Making a variable that starts from 0,..., J-1
# Each market-year, agents are subject to 40 different discrete market choices
cars['y'] = np.resize(np.arange(0,J), N*J)
y = cars['y'].values.reshape((N,J))

In [576]:
y[:, 0] #40 different choices vary for each market-year

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [577]:
res_alt = est.estimate(clogit.q, theta_start, y[:, 0], x)

         Current function value: 0.976207
         Iterations: 95
         Function evaluations: 5972
         Gradient evaluations: 149
Failed to compute std. errs.: got error "Singular matrix"


In [578]:
theta_res_alt = res_alt['theta']

ccp_res_alt = clogit.choice_prob(theta_res_alt, x)

In [579]:
#cars['y'] = np.resize(np.arange(0, M*T), N*J)
#y = cars['y'].values.reshape((N,J))

#cars['y'] = pd.factorize(cars['co'].values)[0]
#y = pd.factorize(cars['co'].values)[0]
#y = y.reshape((N,J))

#cars['brand']=pd.factorize(cars['brand'])[0]
#y = cars['co'].values.reshape((N,J))
#cars['co']=pd.factorize(cars['co'])[0]