# Modeling Demand for Cars with Conditional Logit 

In this problem set, you will replicate part of the results in
Brownstone and Train (1999). You will estimate the conditional logit
model given the available data.
The core of the exercise will be to fill out the file `clogit_ante.py`. 


In [2]:
import numpy as np
from numpy import random
from scipy.stats import norm
from scipy.stats import genextreme
import pandas as pd 

%load_ext autoreload
%autoreload 2

import clogit_ante as clogit
import estimation as est

Data
====

The data consists of a survey of households regarding their preferences
for car purchase. Each household was given 6 options, but the
characteristics that the respondents were asked about was varied. The
surveys were originally conducted in order to illicit consumer
preferences for alternative-fuel vehicles. The data is *stated
preferences*, in the sense that consumers did not actually buy but just
stated what they would hypothetically choose, which is of course a
drawback. This is very common in marketing when historic data is either
not available or does not provide satisfactory variation. The advantage
of the stated preference data is therefore that the choice set can be
varied greatly (for example, the characteristics includes the
availability of recharging stations, which is important for purchase of
electric cars).

The data you will use has $N=4654$ respondents with $J=6$ cars to choose
from. For each household, we let $\mathcal{J}_{i}$ denote the set of
available cars.

If you load the csv-file, `car_data.csv`, you will get a dataframe with 
$NJ = 27,924$ rows. The column `person_id` runs through $0,2,...,N-1$, and
the column `j` is the index for the car, $\{0,1,...,5\}$. The variable 
`binary_choice` is a dummy, =1 for the car chosen by the respondent. 
A conveneint other variable, `y`, is the index for that car, repeated 
and identical for all $J$ rows for each person. The x-variables describe 
the characteristics of the 6 cars that the respondent was asked to choose 
from. 

We will also read in the dataset `car_labels.csv`, which contains the 
variable labels and descriptions for all the variables. 
The lists `x_vars` and `x_lab` will be used throughout as the list of 
explanatory variables we want to work with. 

In order to get the data into a 3-dimensional array, we will access 
the underlying numpy arrays and resize them. For example 

> `x = dat[x_vars].values.resize((N,J,K))`

Note that this will only work because the data is sorted according to 
first `person_id` and then `j`. You can test this by verifying that 
`x[0,:,k]` prints the same as `dat.loc[dat.person_id == 0, x_vars[k]]`. 

In [3]:
lab = pd.read_csv('car_labels.csv', index_col='variable')
lab['description']['price_to_inc']

'Purchase price in thousands of dollars, divided by the natural log of household income in thousands'

In [4]:
# variables to use as explanatory variables
x_lab  = list(lab.iloc[3:-4].label.values) # labels 
x_vars = list(lab.iloc[3:-4].index.values) # variable names 

In [5]:
lab

label  \
variable                                       
person_id                          Person ID   
rownum                               Row num   
binary_choice                  Binary choice   
price_to_inc                Price/ln(income)   
range                                  Range   
acceleration                    Acceleration   
top_speed                          Top speed   
pollution                          Pollution   
size                                    Size   
big_enough                        Big enough   
luggage_space                  Luggage space   
operating_cost                Operating cost   
station_availability    Station availability   
suv                   Sports utility vehicle   
sports_car                        Sports car   
station_wagon                  Station wagon   
truck                                  Truck   
van                                      Van   
ev                           Constant for EV   
commute_x_ev                      Commute*EV   
college_x_ev                      College*EV   
cng                         Constant for CNG   
methanol               Constant for methanol   
college_x_methanol          College*methanol   
not_ev                                Non-EV   
not_cng                              Non-CNG   
j                                 Car number   
y                                 Chosen car   

                                                            description  
variable                                                                 
person_id                                             Person identifier  
rownum                                        Row number in the dataset  
binary_choice          Dummy, =1 if this row is the car that was chosen  
price_to_inc          Purchase price in thousands of dollars, divide...  
range                 Hundreds of miles that the vehicle can travel ...  
acceleration          Seconds required to reach 30 mph from stop, in...  
top_speed             Highest speed that the vehicle can attain, in ...  
pollution             Tailpipe emissions as fraction of comparable n...  
size                  0"mini, 0.1"subcompact, 0.2"compact, 0.3"mid-s...  
big_enough            1 if household size is over 2 and vehicle size...  
luggage_space         Luggage space as fraction of comparable new ga...  
operating_cost        Cost per mile of travel, in tens of cents per ...  
station_availability  Fraction of stations that have capability to r...  
suv                        1 for sports utility vehicle, zero otherwise  
sports_car                             1 for sports car, zero otherwise  
station_wagon                       1 for station wagon, zero otherwise  
truck                                       1 for truck, zero otherwise  
van                                           1 for van, zero otherwise  
ev                               1 for electric vehicle, zero otherwise  
commute_x_ev          1 if respondent commutes less than five miles ...  
college_x_ev          1 if respondent had some college education and...  
cng                   1 for compressed natural gas vehicle, zero oth...  
methanol                         1 for methanol vehicle, zero otherwise  
college_x_methanol    1 if respondent had some college education and...  
not_ev                                       Dummy, =1 if car is not EV  
not_cng                                     Dummy, =1 if car is not CNG  
j                                  Index for the car number (0,1,...,5)  
y                                  Index for the chosen car (0,1,...,5)

In [6]:
dat = pd.read_csv('car_data.csv')
N = dat.person_id.nunique()
J = dat.j.nunique()
K = len(x_vars)

## Scaling variables

Logit is most stable numerically if we ensure that variables are scaled near to $\pm 1$. 

In [7]:
dat['range'] = dat['range'] / 100
dat['top_speed'] = dat['top_speed'] / 100

# scaling by 10 might be overkill 
dat['size'] = dat['size'] / 10
dat['acceleration'] = dat['acceleration'] / 10
dat['operating_cost'] = dat['operating_cost'] / 10

In [8]:
dat['y']

0        0
1        0
2        0
3        0
4        0
        ..
27919    2
27920    2
27921    2
27922    2
27923    2
Name: y, Length: 27924, dtype: int64

In [9]:
y = dat['y'].values.reshape((N,J))
x = dat[x_vars].values.reshape((N,J,K))

In [10]:
dat[x_vars]

price_to_inc  range  acceleration  top_speed  pollution  size  \
0          4.175345   2.50          0.40       0.95       0.60   0.3   
1          4.175345   2.50          0.40       0.95       0.60   0.3   
2          4.817706   4.00          0.60       1.10       0.25   0.2   
3          4.817706   4.00          0.60       1.10       0.25   0.2   
4          5.138886   2.50          0.25       1.40       0.50   0.3   
...             ...    ...           ...        ...        ...   ...   
27919      4.817706   2.00          0.60       1.00       0.00   0.3   
27920      5.138886   0.75          0.25       0.85       0.40   0.3   
27921      5.138886   0.75          0.25       0.85       0.40   0.3   
27922      4.175345   3.50          0.40       1.10       0.25   0.2   
27923      4.175345   3.50          0.40       1.10       0.25   0.2   

       big_enough  luggage_space  operating_cost  station_availability  ...  \
0               0            0.7             0.4                   0.1  ...   
1               0            0.7             0.4                   0.1  ...   
2               0            1.0             0.6                   0.3  ...   
3               0            1.0             0.6                   0.3  ...   
4               0            1.0             0.8                   1.0  ...   
...           ...            ...             ...                   ...  ...   
27919           0            0.7             0.8                   0.0  ...   
27920           0            1.0             0.2                   0.3  ...   
27921           0            1.0             0.2                   0.3  ...   
27922           0            1.0             0.6                   1.0  ...   
27923           0            1.0             0.6                   1.0  ...   

       sports_car  station_wagon  truck  van  ev  commute_x_ev  college_x_ev  \
0               0              0      0    1   0             0             0   
1               0              0      0    0   0             0             0   
2               0              0      0    1   0             0             0   
3               0              1      0    0   0             0             0   
4               0              0      0    1   0             0             0   
...           ...            ...    ...  ...  ..           ...           ...   
27919           0              0      0    1   1             0             0   
27920           0              0      0    0   0             0             0   
27921           0              1      0    0   0             0             0   
27922           0              0      0    0   0             0             0   
27923           0              0      1    0   0             0             0   

       cng  methanol  college_x_methanol  
0        1         0                   0  
1        1         0                   0  
2        0         1                   0  
3        0         1                   0  
4        0         0                   0  
...    ...       ...                 ...  
27919    0         0                   0  
27920    1         0                   0  
27921    1         0                   0  
27922    0         0                   0  
27923    0         0                   0  

[27924 rows x 21 columns]

In [11]:
y.shape

(4654, 6)

In [12]:
y[:, 0]

array([0, 1, 4, ..., 2, 2, 2], dtype=int64)

In [13]:
y[:, 1]

array([0, 1, 4, ..., 2, 2, 2], dtype=int64)

In [14]:
y = y[:, 0] # all J elements are identical along axis=1

In [15]:
y.shape

(4654,)

In [16]:
dat['y']

0        0
1        0
2        0
3        0
4        0
        ..
27919    2
27920    2
27921    2
27922    2
27923    2
Name: y, Length: 27924, dtype: int64

In [17]:
dat[x_vars].head(5)

price_to_inc  range  acceleration  top_speed  pollution  size  big_enough  \
0      4.175345    2.5          0.40       0.95       0.60   0.3           0   
1      4.175345    2.5          0.40       0.95       0.60   0.3           0   
2      4.817706    4.0          0.60       1.10       0.25   0.2           0   
3      4.817706    4.0          0.60       1.10       0.25   0.2           0   
4      5.138886    2.5          0.25       1.40       0.50   0.3           0   

   luggage_space  operating_cost  station_availability  ...  sports_car  \
0            0.7             0.4                   0.1  ...           0   
1            0.7             0.4                   0.1  ...           0   
2            1.0             0.6                   0.3  ...           0   
3            1.0             0.6                   0.3  ...           0   
4            1.0             0.8                   1.0  ...           0   

   station_wagon  truck  van  ev  commute_x_ev  college_x_ev  cng  methanol  \
0              0      0    1   0             0             0    1         0   
1              0      0    0   0             0             0    1         0   
2              0      0    1   0             0             0    0         1   
3              1      0    0   0             0             0    0         1   
4              0      0    1   0             0             0    0         0   

   college_x_methanol  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  

[5 rows x 21 columns]

In [18]:
dat['j'].unique()

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [19]:
dat['price_to_inc'].unique()

array([ 4.1753448 ,  4.8177056 ,  5.1388859 ,  3.3109468 ,  3.586859  ,
        4.4145957 ,  4.0395745 ,  2.7772075 ,  3.2821543 ,  7.0659681 ,
        7.3871485 ,  5.4600663 ,  5.7941569 ,  6.3459814 ,  4.690508  ,
        3.5329841 ,  1.9270822 ,  0.96354111,  1.4453117 ,  6.0700691 ,
        5.2423324 ,  3.0674666 ,  3.8343333 ,  4.0899555 ,  3.8017382 ,
        2.4599482 ,  2.9072116 ,  4.1386835 ,  3.0350346 ,  3.323736  ,
        3.7985554 ,  2.6115068 ,  6.102427  ,  1.2847215 ,  1.6059019 ,
        1.9313856 ,  2.7591223 ,  8.4371306 ,  5.4593198 ,  7.444527  ,
        1.0224889 ,  1.1503    ,  1.2781111 ,  5.9556216 ,  7.9408288 ,
        4.8568222 ,  5.3680666 ,  4.3455777 ,  3.3927834 ,  2.1953304 ,
        2.9936324 ,  1.1241313 ,  6.6218936 ,  3.9704144 ,  4.4667162 ,
        2.9778108 ,  3.7871011 ,  4.0359651 ,  3.0863263 ,  3.5611457 ,
        2.8118444 ,  3.3230888 ,  5.554415  ,  5.8068884 ,  4.2920479 ,
        2.2482626 ,  2.8906233 ,  7.7083289 ,  3.0296809 ,  1.37

# Question 1: 3-dimensional arrays in Numpy

The explanatory variables are $x_{ijk}$, where $i$ denotes individuals,
$j$ cars, and $k$ car attributes. We will be working with these as 3d arrays, so let's do some light warmup. 

## 1.a: Light warmup 

Which of the following commands shows all the price-to-log-income
    values for the cars in the choiceset of individual 1 (and what does
    the other commands give you?).

    a:   x[:,0,0]

    b:   x[0,:,0]

    c:   x[0,0,:]

In [20]:
print(N,J,K)

4654 6 21


In [21]:
# The first x_var
x_vars[0]

'price_to_inc'

In [22]:
# Try to index, and make yourself familiar with a three dimensional array.

# a) The last zero denotes the first x_var, which is price_to_inc
x[:, 0, 0]

# b) Show all the price-to-log-income values for the cars for the first individual
x[0, :, 0]

# c) Show all characteristics for the first individual's choice set of the first car
x[0, 0, :]

array([4.1753448, 2.5      , 0.4      , 0.95     , 0.6      , 0.3      ,
       0.       , 0.7      , 0.4      , 0.1      , 0.       , 0.       ,
       0.       , 0.       , 1.       , 0.       , 0.       , 0.       ,
       1.       , 0.       , 0.       ])

## 1.b: More algebra

Create a 3-dimensional matrix `A` that has dimensions $4 \times 3 \times 2$, and fill it with random draws from a normal distribution. What happens if you matrix post-multiply this by the $2 \times 1$ vector `1 2`? From "common" linear algebra knowledge, what do you expect the dimension of the new matrix is?

---

First, the 'inner' dimensions must match. They do in this case.

Second, the last dimension of a multiplied array determines the dimension of the final matrix. 

Depending if the vector is a 1-D or 2-D array, multiplying the 3-D array would either stay as 3-D, if the vector is 2-D "(2,1)", but become 2-D if it is multiplied with a 1-D vector/array "(2,)", since then the last dimension is 'removed'.

---

In [23]:
rng = random.default_rng(seed=42)
A = rng.normal(size=(4, 3, 2))
print(A, A.shape)

[[[ 0.30471708 -1.03998411]
  [ 0.7504512   0.94056472]
  [-1.95103519 -1.30217951]]

 [[ 0.1278404  -0.31624259]
  [-0.01680116 -0.85304393]
  [ 0.87939797  0.77779194]]

 [[ 0.0660307   1.12724121]
  [ 0.46750934 -0.85929246]
  [ 0.36875078 -0.9588826 ]]

 [[ 0.8784503  -0.04992591]
  [-0.18486236 -0.68092954]
  [ 1.22254134 -0.15452948]]] (4, 3, 2)


In [24]:
C = np.array((1,2))
B = A @ C

print(C, C.shape)

print(B, B.shape)

[1 2] (2,)
[[-1.77525113  2.63158063 -4.5553942 ]
 [-0.50464478 -1.72288901  2.43498185]
 [ 2.32051311 -1.25107558 -1.54901442]
 [ 0.77859848 -1.54672145  0.91348237]] (4, 3)


In [25]:
a = A.reshape(12, 2)
b = (a @ [1, 2]).reshape(4, 3)
print(b)
print(a)
print((B==b).all())

[[-1.77525113  2.63158063 -4.5553942 ]
 [-0.50464478 -1.72288901  2.43498185]
 [ 2.32051311 -1.25107558 -1.54901442]
 [ 0.77859848 -1.54672145  0.91348237]]
[[ 0.30471708 -1.03998411]
 [ 0.7504512   0.94056472]
 [-1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259]
 [-0.01680116 -0.85304393]
 [ 0.87939797  0.77779194]
 [ 0.0660307   1.12724121]
 [ 0.46750934 -0.85929246]
 [ 0.36875078 -0.9588826 ]
 [ 0.8784503  -0.04992591]
 [-0.18486236 -0.68092954]
 [ 1.22254134 -0.15452948]]
True


## 1.c Testing it on the data 
Next, we want to compute $\sum_{k=1}^{K}x_{ijk}\theta_{k}$ using linear algebra. Our  `x` matrix has three dimensions, $N\times J\times K$, and $\theta$ should be $K$ long `(K,)`. 

In [26]:
theta = 0.0 * np.ones((K,))
(x @ theta).shape # should be N by J

(4654, 6)

In [27]:
(x@theta)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

What is the interpretation of the elements of `x @ theta`? 

Every individual's (rows) taste for each of the six cars (columns)

In [28]:
x.sum(axis=2) #Summing all the coefficients of the third dimension ((alternatives))

array([[12.1253448, 11.1253448, 14.8677056, 14.8677056, 13.8888859,
        13.8888859],
       [11.0609468, 12.0609468, 12.986859 , 13.986859 , 11.8145957,
        12.8145957],
       [12.0395745, 13.0395745, 11.1772075, 12.1772075, 11.8821543,
        12.8821543],
       ...,
       [14.204415 , 14.204415 , 12.3068884, 12.3068884, 14.4469948,
        13.4469948],
       [10.2329841,  9.2329841, 11.2270822, 11.2270822, 11.5982626,
        11.5982626],
       [11.2177056, 12.2177056, 10.1888859, 11.1888859, 12.2253448,
        13.2253448]])

In [29]:
theta = np.ones((K,))
x@theta

array([[12.1253448, 11.1253448, 14.8677056, 14.8677056, 13.8888859,
        13.8888859],
       [11.0609468, 12.0609468, 12.986859 , 13.986859 , 11.8145957,
        12.8145957],
       [12.0395745, 13.0395745, 11.1772075, 12.1772075, 11.8821543,
        12.8821543],
       ...,
       [14.204415 , 14.204415 , 12.3068884, 12.3068884, 14.4469948,
        13.4469948],
       [10.2329841,  9.2329841, 11.2270822, 11.2270822, 11.5982626,
        11.5982626],
       [11.2177056, 12.2177056, 10.1888859, 11.1888859, 12.2253448,
        13.2253448]])

# Question 2: Simulating data

Finish `sim_data(N,J,theta)` in `clogit_ante.py` and simulate a dataset. It must return `(y,x)`, where `x` has dimensions ($N\times J\times K$) and `y` ($N\times1$).

The data generating process should be: 
$$u_{ij} = \mathbf{x}_{ij}\theta + \varepsilon_{ij},\quad\varepsilon_{ij}\sim\text{IID Extreme Value Type I},$$

where we will draw the regressors as $x_{ijk} \sim \mathcal{N}(0,1)$ IID for all $(i,j,k)$. The outcome is then $y_i = \arg\max_{j} u_{ij}$. 

***Hints:*** <br>
* Draw `x` as `(N,J,K)` standard normals, 
* Draw `e` ($\varepsilon$) using `genextreme.ppf(uni, c=0)` (the inverse CDF), were `uni` should be an `(N,J)` matrix of uniform draws (`c=0` gives us *Type I*, as needed), 
* To find the argmax over rows, use `np.argmax(axis=1)`. Verify that `y` is `(N,)`. 


In [30]:
N = 1000 # Number of individuals, households etc
K = 3
J = 4 # Number of choices
thetaTrue = np.array([1, 2, 3])

In [31]:
thetaTrue.shape

(3,)

In [32]:
thetaTrue.size

3

In [33]:
# Finish the clogit.sim_data function.
np.random.seed(1337)
y,x = clogit.sim_data(N, thetaTrue, J)

In [34]:
assert y.ndim == 1

In [35]:
y.shape

(1000,)

In [36]:
np.unique(y)

array([0, 1, 2, 3], dtype=int64)

In [37]:
x.shape

(1000, 4, 3)

# Question 3: choice probabilities 

In `clogit_ante.py` finish the functions 
* `starting_values(y,x)`: Just return a $K$-vector of zeros *(what probabilities will arise from this, do you think?)*
* `util(theta, x)`: The deterministic part of utility, max-rescaled: 
$$ v_{ij} = \mathbf{x}_{ij} \theta - K_i, \quad K_i = \max_{j \in \{1,...,J\}}  \mathbf{x}_{ij} \theta. $$ 
Subtracting $K_i$ is called "max-rescaling". 
* `choice_prob(theta, x)`: the $N\times J$ matrix of choice probabilities, given by 
$$ \Pr(y_i = j | \mathbf{x_i}; \theta) = \frac{\exp(v_{ij})}{\sum_{k=1}^J \exp(v_{ik})}. $$ 
Note that if we add a scalar, $K$, to *all* $i$'s utility indices, the choice probabilities are analytically identical (check the algebra!). 

***Hints:*** 
* If `x` has shape `(N,J,K)`, then the matrix product `x @ theta` will return an `(N,J)` matrix. 
* Use `u.max(axis=1)` on an `(N,J)` matrix `u` to compute the max over the rows. 
    * Further, use `u.max(axis=1, keepdims=True)` to get an `(N,1)` vector out, rather than an `(N,)` vector. 

In [38]:
theta0 = clogit.starting_values(y, x)

In [39]:
u = clogit.util(theta0, x)
(u == 0.0).all()

True

In [40]:
ccp = clogit.choice_prob(theta0, x)
(ccp == 0.25).all()

True

In [41]:
ccp

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       ...,
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

# Question 4: Criterion 

In `clogit_ante.py` code up the functions 
* `loglikelihood(theta, y, x)`: loglikelihood contribution: $$ \ell_i (\theta) = \log \Pr( \textcolor{red}{y_i} | \mathbf{x}_i;\theta) = v_{\color{red}{y_i}} - \log \left[ \sum_{j=1}^J \exp(\mathbf{x}_{ij} \theta) \right], $$ 
where $\textcolor{red}{y_i} \in \{0,...,J-1\}$ is the *outcome* for individual $i$ (whereas we earlier used $y_i$ to represent the stochastic variable that is the outcome chosen by $i$, in a mildly abusive notation.)
* `q(theta, y, x)`: the negative loglikelihood criterion, and the function we will give to `est.estimate()`. 

***Hint:*** if you have an `(N,J)` matrix, `v`, and an `(N,)` array of numbers in `0,...,J-1`, you can do it two ways: 
```Python
# in a (slow) loop
ll = np.empty((N,))
for i in range(N): 
    ll[i] = v[i, y[i]]

# or faster
ll = v[range(N), y]
```

In [42]:
thetaTrue

array([1, 2, 3])

In [43]:
theta0

array([0., 0., 0.])

In [44]:
y.shape

(1000,)

In [45]:
x.shape

(1000, 4, 3)

In [46]:
res = est.estimate(clogit.q, thetaTrue, y, x)

Optimization terminated successfully.
         Current function value: 0.454249
         Iterations: 13
         Function evaluations: 56
         Gradient evaluations: 14


In [47]:
tab = pd.DataFrame({v:res[v] for v in ['theta', 'se', 't']}, index=thetaTrue)
tab.index.name = 'theta_true'
tab

theta        se          t
theta_true                               
1           1.132567  0.081938  13.822221
2           2.257761  0.125319  18.016155
3           2.954360  0.160174  18.444683

Expected output:

Optimization terminated successfully.
         Current function value: 0.454249
         Iterations: 14
         Function evaluations: 60
         Gradient evaluations: 15

|   theta_true |   theta |       se |       t |
|-------------:|--------:|---------:|--------:|
|            1 | 1.13255 | 0.081938 | 13.8221 |
|            2 | 2.25778 | 0.125319 | 18.0164 |
|            3 | 2.95431 | 0.160174 | 18.4444 |

# Question 5: Estimation on real data

Estimate the 21 parameters of the model. Check that you are able to
    find the same estimates and standard errors as in Brownstone and
    Train (1998; p. 121).



In [48]:
dat['j']

0        0
1        1
2        2
3        3
4        4
        ..
27919    1
27920    2
27921    3
27922    4
27923    5
Name: j, Length: 27924, dtype: int64

In [49]:
dat['y']

0        0
1        0
2        0
3        0
4        0
        ..
27919    2
27920    2
27921    2
27922    2
27923    2
Name: y, Length: 27924, dtype: int64

In [50]:
N = dat.person_id.nunique()
J = dat.j.nunique()
K = len(x_vars)

y = dat['y'].values.reshape((N,J))
y = y[:, 0] # all J elements are identical along axis=1
x = dat[x_vars].values.reshape((N,J,K))

In [51]:
bt_res = [-.185 , .350 , -.716 , .261 , -.444 , .935 , .143 , .501 , -.768 , .413 , .820 , .637 , -1.437 , -1.017 , -.799 , -.179 , .198 , .443 , .345 , .313 , .228]

In [52]:
tab_bt98 = pd.DataFrame(bt_res, index=x_lab, columns=['Estimate (B&T 1998)'])
tab_bt98

Estimate (B&T 1998)
Price/ln(income)                     -0.185
Range                                 0.350
Acceleration                         -0.716
Top speed                             0.261
Pollution                            -0.444
Size                                  0.935
Big enough                            0.143
Luggage space                         0.501
Operating cost                       -0.768
Station availability                  0.413
Sports utility vehicle                0.820
Sports car                            0.637
Station wagon                        -1.437
Truck                                -1.017
Van                                  -0.799
Constant for EV                      -0.179
Commute*EV                            0.198
College*EV                            0.443
Constant for CNG                      0.345
Constant for methanol                 0.313
College*methanol                      0.228

In [53]:
theta0 = np.array(bt_res)
theta0 = np.zeros((K,))

In [54]:
print(theta0.shape, '\n', y.shape, '\n', x.shape)

(21,) 
 (4654,) 
 (4654, 6, 21)


In [55]:
y.dtype

dtype('int64')

In [56]:
np.linalg.matrix_rank(x)

array([6, 6, 6, ..., 6, 6, 6], dtype=int64)

In [57]:
res = est.estimate(clogit.q, theta0, y, x)

Optimization terminated successfully.
         Current function value: 1.588275
         Iterations: 86
         Function evaluations: 1914
         Gradient evaluations: 87


In [58]:
tab = pd.DataFrame({v:res[v] for v in ['theta', 'se', 't']}, index=x_lab)
tab['B&T 1998'] = tab_bt98
tab['diff'] = tab['theta'] - tab['B&T 1998']
tab

theta        se          t  B&T 1998      diff
Price/ln(income)       -0.185425  0.027200  -6.817204    -0.185 -0.000425
Range                   0.350097  0.026933  12.998896     0.350  0.000097
Acceleration           -0.716185  0.110534  -6.479336    -0.716 -0.000185
Top speed               0.261102  0.079773   3.273060     0.261  0.000102
Pollution              -0.444100  0.100115  -4.435908    -0.444 -0.000100
Size                    0.934345  0.311053   3.003816     0.935 -0.000655
Big enough              0.143350  0.075909   1.888434     0.143  0.000350
Luggage space           0.502489  0.188359   2.667723     0.501  0.001489
Operating cost         -0.767962  0.073376 -10.466127    -0.768  0.000038
Station availability    0.413062  0.096546   4.278411     0.413  0.000062
Sports utility vehicle  0.819471  0.144276   5.679900     0.820 -0.000529
Sports car              0.636111  0.156366   4.068105     0.637 -0.000889
Station wagon          -1.436669  0.065417 -21.961586    -1.437  0.000331
Truck                  -1.016814  0.054530 -18.646856    -1.017  0.000186
Van                    -0.798940  0.053180 -15.023429    -0.799  0.000060
Constant for EV        -0.179025  0.168621  -1.061704    -0.179 -0.000025
Commute*EV              0.198374  0.082343   2.409116     0.198  0.000374
College*EV              0.442935  0.108249   4.091838     0.443 -0.000065
Constant for CNG        0.345061  0.091069   3.789017     0.345  0.000061
Constant for methanol   0.313121  0.103205   3.033971     0.313  0.000121
College*methanol        0.228548  0.088872   2.571671     0.228  0.000548

In [59]:
# Check that results we get is close to the ones in paper.
I_isclose = np.isclose(res['theta'], bt_res, rtol=0.01)
if I_isclose.all(): 
    print(f'All parameters estimated to be within 1% of B&T (1998)')
else: 
    print(f'Some parameters are not matching:\n')
    print(pd.DataFrame({'estimate':res['b_hat'], 'B&T':bt_res, 'close_to_saved':I_isclose}, index=x_lab))

All parameters estimated to be within 1% of B&T (1998)


# Question 6: Price elasticities

> Compute the own-price and cross-price elasticities for all observations $i$ and cars $j$.

As with standard binary probit or logit, the parameter estimates are not
interesting in and of themselves. Instead, we want to compute
*elasticities* that we can interpret and answer interesting questions
with. To do this, recall that an elasticity takes the form

$$\text{elasticity}=\frac{\mathrm{dy}}{y}\frac{x}{\mathrm{d}x}.$$ 
This
formula is useful for computing elasticities numerically: we can
increase $x$ by some small amount, say $10^{-5}$, and measure the change
in $y$. The elasticity is then the relative change in $y$ divided by the
relative change in $x$: $\frac{\Delta y/y}{\Delta x/x}$, or equivalently

$$\text{numerical elasticity}=\frac{\text{pct. change in }y}{\text{pct. change in }x}.$$


***Hint:*** One suggested approach would be: 
1. Evaluate conditional choice probabilities (CCPs) in the baseline setting, `ccp0`, 
2. for each car `j = 0, ..., 5` do: 
    1. make a copy of the dataset, `x2`, 
    2. increase the price  (`k=0`) of car `j` by `h` percent in `x2`, 
    3. evaluate CCPs for `x2`, call it `ccp2`
    4. compute the percent change in CCPs, 
    5. compute the own-price elasticity directly using (1), and save the average elasticity among all cars other than `j` as the cross-price elasticity (averaged among other cars). 

In [60]:
thetahat = res['theta']

In [61]:
# Original choice probabilites
ccp1 = clogit.choice_prob(thetahat, x)

In [62]:
E_own   = np.zeros((N, J))
E_cross = np.zeros((N, J))
dpdx    = np.zeros((N, J))
k_price = 0 

for j in range(J):
    # A. copy 
    x2 = x.copy()
    
    # B. increase price just for car j 
    rel_change_x = 1e-3
    x2[:, j, k_price] *= (1+rel_change_x) # Fill in 

    # C. evaluate CCPs
    ccp2 = clogit.choice_prob(thetahat, x2) # Fill in 
    
    # D. percentage change in CCPs 
    rel_change_y = ccp2/ccp1-1 # Fill in 
    
    # E. elasticities 
    elasticity = rel_change_y/rel_change_x # Fill in 
    
    E_own[:, j] = elasticity[:, j] # Fill in 
    
    k_not_j = [k for k in range(J) if k != j] # indices for all other cars than j -> this list changes as we loop through j
    E_cross[:, j] = elasticity[:, k_not_j].mean(axis=1) # Fill in: Avg. among the cars k_not_j, taking the average over axis=1 (the cars, not the individuals!)

In [63]:
E_cross.shape

(4654, 6)

In [64]:
print(f'Own-price elasticity:  {np.mean(E_own).round(4)}')
print(f'Cross-price elasticity: {np.mean(E_cross).round(4)}')

Own-price elasticity:  -0.652
Cross-price elasticity: 0.1278


Expected output: \\
Own-price elasticity:  -0.652 \\
Cross-price elasticity: 0.1278

### Are Electric Vehicles (EVs) different? 

A lot of policy debate these days is about (EVs). Compare whether demand for EVs is more or less price-sensitive. 

In [65]:
i_ev = 15
x_vars[i_ev] # check that we found the right one 

'ev'

In [66]:
# Create two indexed, from where idx1 is for electric cars
# and idx0 is for non-electric cars.
idx1 = x[:, :, i_ev]==1
idx0 = x[:, :, i_ev]==0 
print(f'Elasticity, EVs:   {np.mean(E_own[idx1]).round(4)}')
print(f'Elasticity, other: {np.mean(E_own[idx0]).round(4)}')

Elasticity, EVs:   -0.7149
Elasticity, other: -0.6311


Elasticity, EVs:   -0.7149 \\
other: -0.6311